### ISSUE TITLE
Fails to get prices for Azure

### ISSUE THREAD

**Issue by vavsab** [controlplane-com/k8s-cost-analyzer#1]
Hi folks.

Trying to run v1.0.5 against Azure k8s cluster but getting this error
![image](https://github.com/controlplane-com/k8s-cost-analyzer/assets/10233442/b0fcadfc-cf5e-4240-a2a8-46ccc84fcc4c)

Is the problem on my side?

**Comment by MajidAbuRmila** [comment]
Hi Ivan,

There is clearly no problem on your side. Basically, the backend couldn't figure out the prices for your Azure node instances.

I made the fix on our end and it is currently available in production. Feel free to try again.

I will keep the issue open until it is settled on your end.

**Comment by vavsab** [comment]
Right now I have no time to test it. If I get same issue again I will let you know. Thank you for quick response!
